apiVersion: v1
kind: Pod
metadata:
  annotations:
    CapacityProvisioned: 0.5vCPU 1GB
    Logging: 'LoggingDisabled: LOGGING_CONFIGMAP_NOT_FOUND'
    kubectl.kubernetes.io/restartedAt: "2023-02-28T18:49:03+01:00"
  labels:
    app.kubernetes.io/component: applicationset-controller
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/part-of: argocd
    eks.amazonaws.com/fargate-profile: argocd
    helm.sh/chart: argo-cd-5.16.1
  name: argo-cd-argocd-applicationset-controller-test-1
  namespace: argocd
spec:
  containers:
  - command:
    - entrypoint.sh
    - argocd-applicationset-controller
    - --argocd-repo-server=argo-cd-argocd-repo-server:8081
    - --enable-leader-election=true
    - --metrics-addr=:8080
    - --probe-addr=:8081
    - --policy=sync
    - --dry-run=false
    - --logformat
    - text
    - --loglevel
    - info
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: quay.io/argoproj/argocd:v2.5.12
    imagePullPolicy: IfNotPresent
    name: applicationset-controller
    ports:
    - containerPort: 8080
      name: metrics
      protocol: TCP
    - containerPort: 8081
      name: probe
      protocol: TCP
    - containerPort: 7000
      name: webhook
      protocol: TCP
    resources:
      requests:
        cpu: 500m
        memory: 4Gi
